#cloud-config
hostname: control-vm
timezone: Europe/Oslo
users:
  - name: hus
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${public_key_control_vm}
      - ${public_key_user1}
      - ${public_key_user2}
    sudo: ALL=(ALL) NOPASSWD:ALL
package_update: true
packages:
  - qemu-guest-agent
  - net-tools
  - curl
  - ansible
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - echo "done" > /tmp/cloud-config.done
