- hosts: k8s_all
  become: true
  tasks:
    - name: Install kubernetes
      become: true
      shell: |
        apt-get update
        apt-get install -y apt-transport-https ca-certificates curl gpg
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        apt-get install -y kubelet kubeadm kubectl
        apt-mark hold kubelet kubeadm kubectl
    - name: Install containerd
      shell: |
        cd /home/hus/setup
        curl -LO https://github.com/containerd/containerd/releases/download/v2.0.4/containerd-2.0.4-linux-amd64.tar.gz
        tar Cxzvf /usr/local containerd-2.0.4-linux-amd64.tar.gz
        curl -o /lib/systemd/system/containerd.service https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        systemctl daemon-reload
        systemctl enable --now containerd
    - name: Install runc
      shell: |
        cd /home/hus/setup
        curl -LO https://github.com/opencontainers/runc/releases/download/v1.2.6/runc.amd64
        install -m 755 runc.amd64 /usr/local/sbin/runc
        chmod +x /usr/local/sbin/runc
    - name: Install CNI plugins
      shell: |
        cd /home/hus/setup
        curl -LO https://github.com/containernetworking/plugins/releases/download/v1.6.2/cni-plugins-linux-amd64-v1.6.2.tgz
        mkdir -p /opt/cni/bin
        tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.6.2.tgz
    - name: Enable IPv4 forwarding
      become: true
      shell: |
        sed -i '/^net.ipv4.ip_forward/d' /etc/sysctl.conf
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        sysctl -p