apiVersion: v1
kind: Secret
metadata:
  name: myfront-secrets
  namespace: default
type: Opaque
data:
  VITE_TOURNAMENT_DETAILS_URL: ${vite_tournament_details_url}
  VITE_TOURNAMENT_WEBSOCKET_URL: ${vite_tournament_websocket_url}
---
apiVersion: v1
kind: Secret
metadata:
  name: myanalyzer-secrets
  namespace: default
type: Opaque
data:
  CHESS_LIVE_DB: ${chess_live_db}
  REDIS_URL: ${redis_url}
---
apiVersion: v1
kind: Secret
metadata:
  name: myapi-secrets
  namespace: default
type: Opaque
data:
  CHESS_LIVE_DB: ${chess_live_db}
  REDIS_URL: ${redis_url}
  OPENAI_API_KEY: ${openai_api_key}
---
apiVersion: v1
kind: Secret
metadata:
  name: myloader-secrets
  namespace: default
type: Opaque
data:
  CHESS_LIVE_DB: ${chess_live_db}
  REDIS_URL: ${redis_url}
  OPENAI_API_KEY: ${openai_api_key}
---
apiVersion: v1
kind: Secret
metadata:
  name: mymigrate-secrets
  namespace: default
type: Opaque
data:
  CHESS_LIVE_DB: ${chess_live_db}