# k8s-master-p2-playbook.yaml
- hosts: k8s_master
  become: true
  tasks:
    - name: Install helm
      shell: |
        cd /home/hus/setup
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Install cilium
      shell: |
        helm repo add cilium https://helm.cilium.io
        helm repo update
        helm install cilium cilium/cilium --namespace kube-system

    - name: Install local-path-provisioner
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml
        kubectl patch storageclass local-path -p "{\"metadata\": {\"annotations\": {\"storageclass.kubernetes.io/is-default-class\": \"true\"}}}"