- name: Install kubernetes
  hosts: k8s_all
  become: true
  tasks:
    - name: Install kubernetes
      shell: |
        apt-get update
        apt-get install -y apt-transport-https ca-certificates curl gpg
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        apt-get install -y kubelet kubeadm kubectl
        apt-mark hold kubelet kubeadm kubectl
    - name: Install containerd
      shell: |
        cd /home/hus
        curl -LO https://github.com/containerd/containerd/releases/download/v2.0.4/containerd-2.0.4-linux-amd64.tar.gz
        tar Cxzvf /usr/local containerd-2.0.4-linux-amd64.tar.gz
        curl -o /lib/systemd/system/containerd.service https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        systemctl daemon-reload
        systemctl enable --now containerd
    - name: Install runc
      shell: |
        cd /home/hus
        curl -LO https://github.com/opencontainers/runc/releases/download/v1.2.6/runc.amd64
        install -m 755 runc.amd64 /usr/local/sbin/runc
        chmod +x /usr/local/sbin/runc
    - name: Install CNI plugins
      shell: |
        cd /home/hus
        curl -LO https://github.com/containernetworking/plugins/releases/download/v1.6.2/cni-plugins-linux-amd64-v1.6.2.tgz
        mkdir -p /opt/cni/bin
        tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.6.2.tgz
    - name: Enable IPv4 forwarding
      shell: |
        sed -i '/^net.ipv4.ip_forward/d' /etc/sysctl.conf
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        sysctl -p

#####
- name: Setup cluster with master
  hosts: k8s_master
  become: true
  tasks:
    - name: Setup kubeadm
      shell: |
        kubeadm init --config=/home/hus/kubeadm_init_config.yaml
    - name: Setup kubeconfig
      shell: |
        mkdir -p /home/hus/.kube
        cp /etc/kubernetes/admin.conf /home/hus/.kube/config
        chown hus:hus /home/hus/.kube/config

#####
- name: Join cluster with workers
  hosts: k8s_workers
  become: true
  tasks:
    - name: Kubeadm join
      shell: |
        kubeadm join --config=/home/hus/kubeadm_join_config.yaml

#####
- name: Configure cluster with master
  hosts: k8s_master
  become: false
  tasks:
    - name: Install helm
      shell: |
        cd /home/hus
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    - name: Install cilium
      shell: |
        helm repo add cilium https://helm.cilium.io
        helm repo update
        helm install cilium cilium/cilium --namespace kube-system
    - name: Install local-path-provisioner
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml
        kubectl patch storageclass local-path -p "{\"metadata\": {\"annotations\": {\"storageclass.kubernetes.io/is-default-class\": \"true\"}}}"